// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package pinecone

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	DestinationConfigApiKey    = "apiKey"
	DestinationConfigHost      = "host"
	DestinationConfigNamespace = "namespace"
)

func (DestinationConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		DestinationConfigApiKey: {
			Default:     "",
			Description: "APIKey is the API Key for authenticating with Pinecone.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		DestinationConfigHost: {
			Default:     "",
			Description: "Host is the whole Pinecone index host URL.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		DestinationConfigNamespace: {
			Default:     "",
			Description: "Namespace is the Pinecone's index namespace. Defaults to the empty\nnamespace. It can contain a [Go template](https://pkg.go.dev/text/template)\nthat will be executed for each record to determine the namespace.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
	}
}
