version: 2.2
pipelines:
  - id: file-to-pinecone
    status: running
    connectors:
      - id: file.in
        type: source
        plugin: builtin:file
        settings:
          path: ./file.in
      - id: pinecone.out
        type: destination
        plugin: standalone:conduit-connector-pinecone
        name: pinecone-destination
        settings:
          apiKey: ${API_KEY}
          host: ${HOST_URL}
          opencdc.Record.format: template
          opencdc.Record.format.options: '{{ printf "%s" .Payload.After }}'
