name: test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-pinecone:
    environment: ci  # Add this line
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Run all tests
        run: make test GOTEST_FLAGS="-v -count=1"
        env:
          API_KEY: ${{ secrets.API_KEY }}
          HOST_URL: ${{ secrets.HOST_URL }}
